DAO3
YuraBondarenko/dao pull request #1
Opened 2021-01-11 16:08 UTC by YuraBondarenko

created model for Car, Driver and Manufacturer
created Storage for manufacturers
created dao and service for Manufacturer
created annotation Dao, Inject and Service

2021-01-11 16:47 UTC, Baldinini requested changes

2021-01-11 16:47 UTC, Baldinini commented on src/main/java/core/basesyntax/Main.java
> +        System.out.println(manufacturerService.get(3L));
create constant

2021-01-11 16:47 UTC, Baldinini commented on src/main/java/core/basesyntax/Main.java
> +        manufacturerService.delete(1L);
same

2021-01-11 16:47 UTC, Baldinini commented on src/main/java/core/basesyntax/dao/ManufacturerDaoImpl.java
> +        Manufacturer newManufacturer = getAll().stream()
```suggestion
        Manufacturer newManufacturer = get(manufacturer.getId()).get();
```

2021-01-11 18:27 UTC, Baldinini approved these changes

2021-01-12 07:42 UTC, RomanDubovskyi requested changes

2021-01-12 07:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/dao/ManufacturerDaoImpl.java
> +        return newManufacturer;
we should iterate the list to find the needed object, current approach won't work correctly when you delete element from list and then try to update it

2021-01-12 07:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/dao/ManufacturerDaoImpl.java
> +        return delete(get(id).get());
use removeIf instead here that will be more reliable

2021-01-12 07:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/model/Car.java
> +    public Car(Long id, String model, Manufacturer manufacturer, List<Driver> drivers) {
checklist

2021-01-12 11:17 UTC, RomanDubovskyi requested changes

2021-01-12 11:17 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/dao/ManufacturerDaoImpl.java
> +        return Storage.manufacturers.remove(get(id).get());
```suggestion
        return Storage.manufacturers.removeIf(m -> m.getId().equals(id));
```
and we won't need to use get method inside

2021-01-12 11:17 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/dao/ManufacturerDaoImpl.java
> +        Storage.manufacturers.set(index, manufacturer);
```suggestion
                .forEach(i -> Storage.manufacturers.set(i, manufacturer);
```

2021-01-12 11:17 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/model/Car.java
> +    public Car(Long id, String model, Manufacturer manufacturer, List<Driver> drivers) {
what about this comment?

2021-01-12 12:22 UTC, RomanDubovskyi approved these changes

2021-01-12 12:56 UTC, merged