Hw26 dao9 servlet3
YuraBondarenko/dao pull request #7
Opened 2021-01-22 15:29 UTC by YuraBondarenko

2021-01-22 18:52 UTC, Baldinini requested changes

2021-01-22 18:52 UTC, Baldinini commented on src/main/webapp/WEB-INF/views/driver/create.jsp
> +<a href="${pageContext.request.contextPath}/manufacturers">Show all drivers</a>
if you want to show all drivers why you use `/manufacturers` ?

2021-01-22 18:52 UTC, Baldinini commented on src/main/java/core/basesyntax/model/Driver.java
> +        return Objects.hash(id, name, licenceNumber, login);
if you use password in Objects.equals you should you it in hashCode()

2021-01-22 18:52 UTC, Baldinini commented on src/main/java/core/basesyntax/controllers/driver/CreateDriverController.java
> +        if (driverService.findByLogin(login).isPresent()) {
you use unique login, you catch exception before this checking

2021-01-22 19:08 UTC, yurwing commented on src/main/java/core/basesyntax/controllers/driver/CreateDriverController.java
> +        if (driverService.findByLogin(login).isPresent()) {
I catch exception when I use driverService.create(driver)

2021-01-22 19:30 UTC, Baldinini approved these changes

2021-01-25 17:06 UTC, Sofasmile requested changes

2021-01-25 17:06 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/CarDaoJdbcImpl.java
> +                String password = resultSet.getObject("password", String.class);
діставати тут пароль не зовсім коректно з точки безепеки

2021-01-25 17:06 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Driver.java
> +                && Objects.equals(login, driver.login);
паролі також варто додати до eqauls and hashcode

2021-01-25 17:12 UTC, YuraBondarenko commented on src/main/java/core/basesyntax/model/Driver.java
> +                && Objects.equals(login, driver.login);
в этом есть смысл? (звучит грубо, но это не так:) ) логин у нас все равно уникальный + сравнивать по паролям мне кажется не очень безопасно

2021-01-26 09:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Driver.java
> +                && Objects.equals(login, driver.login);
якщо логін унікальний - загалом можна обійтись без паролів. Проте порівняння паролів в equals не несе ніякої загрози. Адже ми зазвичай не дістаємо з БД пароль, тому тут він зачасту буде null
Але з точки зору констистентності, все ж таки краще додавати всі поля

2021-01-26 09:12 UTC, Sofasmile approved these changes

2021-01-26 20:23 UTC, merged